name: monitoring

services:
    beszel:
        image: henrygd/beszel:latest
        container_name: beszel
        restart: unless-stopped
        environment:
            APP_URL: ${BESZEL_APP_URL}
        ports:
            - 8090:8090
        volumes:
            - /DATA/AppData/beszel/data:/beszel_data
            - /DATA/AppData/beszel/socket:/beszel_socket
        networks:
            newt_public:
                ipv4_address: 10.5.1.4
                ipv6_address: fd25:5000:1000:1::4

    beszel-agent:
        image: henrygd/beszel-agent:alpine
        container_name: beszel-agent
        depends_on:
            - beszel
        restart: unless-stopped
        network_mode: host
        volumes:
            - /DATA/AppData/beszel/agent/data:/var/lib/beszel-agent
            - /DATA/AppData/beszel/socket:/beszel_socket
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /DATA/Media:/extra-filesystems/sda3:ro
        environment:
            LISTEN: /beszel_socket/beszel.sock
            HUB_URL: ${BESZEL_HUB_URL}
            TOKEN: ${BESZEL_TOKEN}
            KEY: "${BESZEL_KEY}"
        cap_add:
            - SYS_RAWIO
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdb:/dev/sdb

    uptime-kuma:
        image: louislam/uptime-kuma:2
        container_name: uptime-kuma
        restart: unless-stopped
        volumes:
            - /DATA/AppData/uptime-kuma/data:/app/data
        ports:
            - "3001:3001"
        networks:
            newt_private:
                ipv4_address: 10.5.100.5
                ipv6_address: fd25:5000:1000:100::5

    diun:
        image: crazymax/diun:latest
        container_name: diun
        restart: unless-stopped
        command: serve
        volumes:
            - "/DATA/AppData/diun/data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            - "TZ=America/Sao_Paulo"
            - "DIUN_WATCH_WORKERS=15"
            - "DIUN_WATCH_SCHEDULE=0 8,16 * * *"
            - "DIUN_WATCH_JITTER=30s"
            - "DIUN_PROVIDERS_DOCKER=true"
            - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
            - "DIUN_NOTIF_APPRISE_ENDPOINT=http://apprise:8000"
            - "DIUN_NOTIF_APPRISE_TOKEN=${APPRISE_TOKEN}"
        labels:
            - "diun.enable=true"
        networks:
            notify:
                ipv4_address: 10.60.1.2
                ipv6_address: fd25:6000:1000:1::2

networks:
    newt_public:
        external: true
    newt_private:
        external: true
    notify:
        external: true