name: monitoring

services:
    beszel:
        image: henrygd/beszel:latest
        container_name: beszel
        restart: unless-stopped
        environment:
            APP_URL: ${BESZEL_APP_URL}
        ports:
            - 8090:8090
        volumes:
            - /DATA/AppData/beszel/data:/beszel_data
            - /DATA/AppData/beszel/socket:/beszel_socket

    beszel-agent:
        image: henrygd/beszel-agent:latest
        container_name: beszel-agent
        depends_on:
            - beszel
        restart: unless-stopped
        network_mode: host
        volumes:
            - /DATA/AppData/beszel/agent/data:/var/lib/beszel-agent
            - /DATA/AppData/beszel/socket:/beszel_socket
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /DATA/Media:/extra-filesystems/sda3:ro
        environment:
            LISTEN: /beszel_socket/beszel.sock
            HUB_URL: ${BESZEL_HUB_URL}
            TOKEN: ${BESZEL_TOKEN}
            KEY: "${BESZEL_KEY}"
