name: homeassistant
services:
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:stable
        hostname: homeassistant
        network_mode: host
        environment:
            TZ: America/Sao_Paulo
        privileged: true
        restart: unless-stopped
        volumes:
            - /DATA/AppData/homeassistant/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro