server:
    #auto-trust-anchor-file: "/var/lib/unbound/root.key"

    interface: 0.0.0.0
    interface: ::0

    access-control: 172.20.0.0/16 allow
    access-control: fd25:1000:1000:100::/64 allow

    cache-min-ttl: 300
    cache-max-ttl: 86400

    qname-minimisation: yes
    aggressive-nsec: yes
    prefetch: yes
    serve-expired: yes
    so-sndbuf: 0
