name: proxy

services:
    newt:
        container_name: newt
        image: fosrl/newt:latest
        restart: unless-stopped
        environment:
            - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
            - NEWT_ID=${NEWT_ID}
            - NEWT_SECRET=${NEWT_SECRET}
        networks:
            newt_public:
                ipv4_address: 10.5.1.100

    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        image: jc21/nginx-proxy-manager:latest
        restart: unless-stopped
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
            - "81:81/tcp"
        environment:
            TZ: "America/Sao_Paulo"
            PUID: 1000
            PGID: 1000
        volumes:
            - /DATA/AppData/nginx-proxy-manager/data:/data
            - /DATA/AppData/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        networks:
            newt_public:
                ipv4_address: 10.5.1.2

networks:
    newt_public:
        name: newt_public
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 10.5.1.0/24
                - subnet: fd25:5000:1000:1::/64
