name: portainer
services:
    portainer:
        container_name: portainer
        hostname: portainer
        image: portainer/portainer-ce:lts
        network_mode: bridge
        ports:
            - "8000:8000/tcp"
            - "9001:9001/tcp"
            - "9443:9443/tcp"
        restart: always
        volumes:
            - type: bind
              source: /DATA/AppData/portainer
              target: /data
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
networks:
    default:
        name: portainer_network